package lexico;

public enum Terminales {
	 IF , WHILE ,DO , FUNCTION,RETURN,VAR,INT,CHARS,BOOL,PARENIZ,PARENDE,LLAVEIZ,LLAVEDE,COMA,SALTO,ID,
	 ENT,CAD,IGUAL,NOIGUAL,MENOR,MAYOR,SUMA, RESTA, DIV, MULT, ASSIGN,WRITE,PROMPT,AND,ASSIGNY, ERROR, COMENTARIO, EOF, lambda,$
}
